### ISSUE TITLE
Option for containment on ui-dialog or/and improvement of documentation

### ISSUE THREAD

**Issue by lichtkabouter** [jquery/api.jqueryui.com#259]
Within ui-dialog there is a way to set the appendTo. I presumed it would feed the boundries to _makeDraggable as well. As I found out the containment of a dialog is set to 'document'.

I would suggest making an option which can be used to set the containment:
$( "selector" ).dialog( { containment: "foo" } );

The short-term solution to handle this is by extending the documentation by showing how containment can be set without editing sources:
 $( "selector" ).dialog().dialog( "widget" ).draggable( { containment: "foo" } );

**Comment by scottgonzalez** [comment]
This gets way too complicated because it also affects positioning. The current implementation supports the overwhelming majority of use cases. If you need fine grained control, you should do it yourself.

On a side note, this is not the place to suggest API changes, that would be http://bugs.jqueryui.com.
